### ISSUE TITLE
Custom Images

### ISSUE THREAD

**Issue by moredure** [packethost/packet-images#32]
Is it possible to provide custom image setup using private github repository?

**Comment by displague** [comment]
@moredure Apologies for the long delay here 😞.

Incase you missed it, we opensourced many of the components involved in the deployment of packet-images 🎉 . 

* https://github.com/tinkerbell
* https://www.packet.com/blog/open-sourcing-tinkerbell/

To answer your question, I don't believe private GitHub repositories could be used currently.

See https://www.packet.com/developers/docs/servers/operating-systems/custom-images/ for some more detail on how to use a public repository.

With an HTTP git URL that contains a token (as path or query parameters) this would be possible. I don't believe that feature is offered through Github.

https://stackoverflow.com/questions/39827530/github-get-on-private-repo-with-access-token describes a solution that almost fits, except the result is a JSON API response (containing the file) rather than a git repository.  

For a glimpse into the limitations, take a look at some of the related code here: https://github.com/tinkerbell/osie/blob/8292b4f1e8b510e43c1679e03cb210ddb3c872fc/osie-runner/handlers.py#L313-L330.  

If this is something that you are interested in pursuing, https://github.com/tinkerbell/osie/issues would be a good place to start. https://github.com/tinkerbell/proposals may be needed to plot out a more elaborate intention.  It's also worth noting that there are no guarantees that any particular Tinkerbell enhancement will make it back to Packet.

I'm closing this issue, but I do encourage and welcome more of your feedback in this thread or at the Tinkerbell project.
