### ISSUE TITLE
CentOS aarch64 builds from a very old FROM line

### ISSUE THREAD

**Issue by vielmetti** [packethost/packet-images#4]
In https://github.com/packethost/packet-images/blob/master/distros/centos/7/aarch64/Dockerfile the first line pulls from https://hub.docker.com/r/jefby/centos-arm64/ which hasn't been updated in over a year.

**Comment by mmlb** [comment]
@vielmetti the base image for that has been changed to `project31/aarch64-centos` which is only slightly younger @7months since last push. I just updated the image and ran a `yum update` which gets us the latest packages. We are planning to have monthly releases with updates for all distros (starting may hopefully).

I think we can close this issue.
